### ISSUE TITLE
Disagreement between pympc and MPChecker 

### ISSUE THREAD

**Issue by AngusWright** [Lyalpha/pympc#5]
I'm trying to use pympc to script a large set of queries, but I'm finding that pympc returns MP positions that don't agree with what I get using the MPChecker webform for the equivalent search (and the MPChecker position matches the imaging, whereas pympc does not). Examples below: 

Using the example query from the README, I find the position of Ceres using pympc to be: 

```
         name          ra        dec  separation    mag                                         xephem_str
0       Ceres  230.096919 -11.812019  278.783199   8.83  Ceres,e,10.58680000,80.26642000,73.53162000,2....
``` 
which in hms/dms is `15 20 23.26 -11 48 43.27 `

However the equivalent search from MPChecker returns Ceres at: 
```    
(1) Ceres           15 20 06.6 -11 46 28 
``` 
which is different by 2 armin in declination and 15 arcsec in RA. Both are computed using the same observatory (950 in this case), and the time from the README example. Any idea where this difference is coming from, and/or what I can do to get the results from pympc to match with the MPChecker ones?

**Comment by Lyalpha** [comment]
Yeah, this in unfortunately a limitation of `pympc`, in that it relies on the latest catalogue of elements downloaded from the MPC. It was really built to do fast, local checking in real-time rather than for historical epochs.

In this case, it is trying to back-propagate an orbit ~3 years, and so the uncertainties compound to give only ~arcminutes accuracy.

You can test it again using 2022-08-01 as your epoch, for example. In this case, I find a ~2 arcsecond agreement with where MPC says Ceres is on that epoch.

The bottom of the readme has a bit of information on this, although maybe it is not too clear. I would only trust the positions at ~arcsec accuracy within a few months of the date of the MPCORB database you've downloaded via `pympc.update_catalogue()` (you can see the times at https://www.minorplanetcenter.net/data). I don't know if historical versions are available via the MPC.

**Comment by AngusWright** [comment]
Ok, understood :+1: Probably worth adding a runtime warning for users who query dates outside of the expected window, so that they know that they're using the code in an unintended fashion? 

I will continue hunting for a non-web-based MPChecker alternative. Thanks!

**Comment by Lyalpha** [comment]
> Ok, understood +1 Probably worth adding a runtime warning for users who query dates outside of the expected window, so that they know that they're using the code in an unintended fashion?

It's on the list (#2) :smile: 

> I will continue hunting for a non-web-based MPChecker alternative. Thanks!

I couldn't find anything that allowed for long-baseline + accurate checking. It depends what time-frame you need to be able to search within. If it's not huge then you could enquire at MPC if it's possible to one-off grab a selection of historical MPCORB catalogues covering your time-frame every serveral months and then query the nearest-in-time catalogue for each call.

https://ssp.imcce.fr/webservices/skybot/ is an online alternative with an API a bit more suited for large numbers of calls - although it is still rate limited of course.
